import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button, PageHeader, Typography, Spin } from "antd";
import { useSession } from "next-auth/react";
import RegisterTabs from "../components/RegisterTab";

const { Title } = Typography;

export default function Home() {
  const { data: session, status } = useSession();
  console.log({ session, status });

  if (status === "loading") {
    return (
      <div className={styles.homeBanner}>
        <br />
        <Spin size="large" />
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>User Registry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.homeBanner}>
        {!session ? (
          <h2>Sign in to access the registry</h2>
        ) : (
          <h2>Welcome, {session.user.name}!</h2>
        )}
        {session && <RegisterTabs session={session} />}
      </main>
    </>
  );
}
